name: ci
on: [push, pull_request]  
jobs:
  test:
    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['20.16.x']
        os: ['ubuntu-latest', 'windows-latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm
        run: |
          npm ci
          npm run test
